#!/bin/bash

export DIR=$(dirname $(readlink -f ${0}))
export IPList=$(echo 192.168.0.{1..254})
export APP_IPS=$(echo ${IPList} | tr ' ' ',')
export APP_DNSNAMES="dashboard"

# export APP_CAONLY=true
export APP_CACOMMON=k8s
export APP_CAORG=k8s
export APP_CAUNIT=devops
export APP_COMMON=dashboard
export APP_ORG=dashboard
export APP_UNIT=devops
# export APP_PATH="tls"
export APP_KEY="cluster/tls/dashboard"
export APP_CERT="cluster/tls/dashboard"
# export APP_KEY="cluster/tls/dashboard.key"
# export APP_DEBUG=true
set -x
# export APP_OVERWRITE=true
echo export APP_OVERWRITE=${APP_OVERWRITE}

go build -tags netgo -ldflags '-w -s' ../certinfo
go build -tags netgo -ldflags '-w -s' 
./certgen
./certinfo --file cluster/tls/ca.crt        --fingerprint
./certinfo --file cluster/tls/dashboard.crt --fingerprint
./certinfo -file cluster/tls/ca.crt 
./certinfo -file cluster/tls/dashboard.crt 
